Input scene: 	/var/www/data/fb703f30-e525-49f4-b4ab-4ce2560137ca/opensfm/undistorted/reconstruction.nvm
Input mesh: 	/var/www/data/fb703f30-e525-49f4-b4ab-4ce2560137ca/odm_meshing/odm_mesh.ply
Output prefix: 	/var/www/data/fb703f30-e525-49f4-b4ab-4ce2560137ca/odm_texturing/odm_textured_model_geo
Datacost file: 	
Labeling file: 	
Data term: 	gmi
Smoothness term: 	potts
Outlier removal method: 	gauss_clamping
Tone mapping: 	none
Apply global seam leveling: 	True
Apply local seam leveling: 	True
